### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by luopangda** [gwuhaolin/reflv#1]
RTMP_Connect0, failed to connect socket. 10061 (Unknown error)
rtmp://live.wuhaolin.cn/live/reflv: Unknown error occurred

执行完这个ffmpeg -re -i demo.flv -c copy -f flv rtmp://live.wuhaolin.cn/live/reflv  命令后出现了这个错误，请问是因为什么？

**Comment by gwuhaolin** [comment]
因为我的音视频服务器 live.wuhaolin.cn 关闭了，一直开着很烧钱。
